### PR TITLE
Added functionality to move windows with MouseMove instead of MouseDown

### PR DESCRIPTION
**Pull request by jstampe**
See https://github.com/dmarcotte/easy-move-resize/issues/21

Added functionality to move windows like Zooom/2.
No functionality to resize windows without pressing right mouse button.

### CODE REVIEW

**Comment by dmarcotte** [comment]
Thanks @jstampe!  This is looking really good.  I'm going to tinker with it for a bit and see if we can address resize configurability too, so more news hopefully soon.

**Comment by dmarcotte** [comment]
Update: still looking at this, and feeling optimistic.   Hopefully I can squeeze out enough time before too long to finish my tinkering.  Thanks for your patience @jstampe.

**Comment by albertferras** [comment]
Is this going to fix the lag issues when moving windows? (mouse moves, window moves with delay)

**Comment by bartskowron** [comment]
any update on this? MouseMove is a way sexier, especially on touchpad, instead of clicking.
Regarding the resize feature, what about a possibility to have different hotkeys for moving and resizing? E.g. ctrl+move = move, option+move = resize.

**Comment by cablehead** [comment]
I'm an ex-zooom/2 user too. I configured zooom/2 to use Command+Shift, mouse move to move windows and Alt+Shift to resize. I've been searching for a simple replacement. This PR sounds like just the thing!

**Comment by elFua** [comment]
## For trackpad users:

As a workaround, with the current master version it is possible to avoid the need to click on the touchpad if you enable the **three finger drag** from **_System Preferences_** > **_Accessibility_** > **_Mouse and Trackpad_** > [enable] **_Enable dragging_** > [select] **three finger drag**.

screen shot 2018-03-10 at 12 00 49 pm

**Comment by CodisRedding** [comment]
@elFua  This is closer, but it messes with my existing settings

**Comment by elFua** [comment]
Build instructions for the hover move-resize version from @feinstruktur

https://github.com/dmarcotte/easy-move-resize/issues/21#issuecomment-402563393

**Pull request closed without merging**
