### PR TITLE
WIP: Move only tracking

### PR DESCRIPTION
**Pull request by finestructure**
I've been using Better Touch Tool for ages to provide a similar x windows inspired move and resize behaviour to your EMR project. When BTT broke in macOS Mojave I looked for a replacement and found EMR.

One big difference in how I used BTT was that I had mapped different key modifiers for move and resize and solely required those. This allows me to move and resize without pressing any mouse keys - which is great for track pad use and to avoid bringing the window into the foreground.

Now it was easy to hack EMR into supporting my mode (calling it "hover mode" for lack of a better term) and I spent a bit of time setting up a preferences window for it. Since it requires two sets of modifiers instead of just one, the menu based system was a bit awkward.

Here's what this looks like:

screen shot 2018-06-17 at 12 40 02

I also spent quite a bit of time trying to support both the existing "click mode" as well as my new "hover mode" but it turns out that I've currently simply broken "click mode" despite my attempts to keep it functional 😞

I feel like it shouldn't be too hard to re-instate it and I'll try to spend some more time on it.

In the interim I wanted to open up this PR to see what your thoughts are.

The changes are quite sweeping - apologies for that as well. It started out small and then it kinda got out of control 😅

### CODE REVIEW

**Comment by feinstruktur** [comment]
Hi Daniel, I haven't heard back from you so I wanted to check how to best proceed with this. I've been using my version for a few months now and it's been working great.

I'd love to make this available as I would imagine others might find this useful as well. However, without fixing the click mode that I've broken in the process this obviously cannot be merged in.

The easiest path forward would be for me to just maintain a fork with the move mode as the only available option, at least until the click mode gets fixed.

If I do so, should I rather rename the project so it doesn't cause confusion?

What are your thoughts?

**Comment by dmarcotte** [comment]
Hey @feinstruktur, thanks for the pull request, thanks for this follow-up note, and thanks for the patience.  

This is really intriguing work that pushes the project in a direction I'd like to go, but I'm not sure when I'll be able to dedicate the time it needs.  Hopefully before not too long, but in the meantime, a renamed fork sounds like a fine way forward.  Please feel free to make that happen, and thanks again for your help here!

**Comment by finestructure** [comment]
@dmarcotte thanks a lot for your feedback and apologies for the very late reply. (Had an outdated email set on my Github account and missed all notifications :/ )

I'll look into cleaning my fork up and disambiguating it and will close the PR for now.

Thanks again for this project!

**Comment by finestructure** [comment]
@dmarcotte I've finally gotten around to prepping a release 😅 I've got a branch ready which just needs some documentation updates but before I publish this I wanted to let you have a look: https://github.com/finestructure/Hummingbird/tree/release-prep

I'm not 100% sure how to deal with the license.txt, so I've just added a line with my name to it. Does that make sense to you?

**Comment by finestructure** [comment]
Looks like that's the way to go apparently: https://softwareengineering.stackexchange.com/a/386584

I should add that I went through and changed lots of `EMR` prefixes to `HB`. That's not to hide any of Hummingbird's origins but just my terrible code tidiness OCD kicking it (prefixes matching project name) 😅 I hope that's alright.

Please do also let me know if attribution in the Readme is adequate in your opinion.

**Comment by dmarcotte** [comment]
Look great, @finestructure!  Congrats on your project coming together, and thanks again for being careful with the attribution.  I really appreciate it.

**Pull request closed without merging**
