### PR TITLE
Resolves dmarcotte/easy-move-resize#38 - Take two

### PR DESCRIPTION
**Pull request by patchon**
Cleaned up this PR a bit.
- Removed the disabled state.
- Removed debug log messages.
- Removed my personal workspace settings.
- Also gave some love for the readme and added a newer screenshot (put it in a separate commit so just remove them if you don't like it). 

Making a new PR since I wasn't really sure how to delete the build from git.  Tried `git filter-branch`, but I didn't like the warning message ;)

### CODE REVIEW

**Comment by dmarcotte** [comment]
Thanks @patchon!  Will push a release for this very soon.

**Comment by magnetikonline** [comment]
@dmarcotte you've called your release `Option for middle-click move` - when it _should_ be `Option for middle-click resize` 😄

**Comment by dmarcotte** [comment]
Aha!  Thanks for the heads up---fixed :)

**Comment by magnetikonline** [comment]
Not a problem - I was actually keen for middle click move 😄  as an option!

**Pull request merged**
