### PR TITLE
Disable in specific apps

### PR DESCRIPTION
**Pull request by moffatman**
Added a new menu item to disable dragging the last app which was just dragged
Added a new menu list to re-enable any app which was disabled previously

Fixes https://github.com/dmarcotte/easy-move-resize/issues/39

### CODE REVIEW

**Comment by dmarcotte** [comment]
This is great!  Thanks @moffatman.  I really like the design of using "last app" to let the user pick what to disable, and I like how easy/clear it is to re-enable.

I ran into one issue testing this change: it seems to break some resize calculations.  The most reliable way to reproduce is to initiate a resize near the top-left corner of an app, and note that the resize is sometimes dramatically wrong ([IntelliJ IDEA](https://www.jetbrains.com/idea/download) seemed to be one of the apps that behaves particularly poorly under this bug), and even when it mostly works, it resizes from the bottom-right corner, rather than the top-left corner as desired/expected.  Does that makes sense?

@CianMclennan would you have a bit of time to do a review here?  Your eyes/input would be much appreciated

**Comment by moffatman** [comment]
@dmarcotte Good catch, it turns out I assumed that only one of the if-statements would ever be entered, but in the resize case two different ones are involved for the same event. So the resize was using the dimensions of the previous window in some calculations. I was able to reproduce the issue and found this latest change fixed it. Let me know if it works for you as well.

**Comment by dmarcotte** [comment]
@moffatman thanks for much for the quick update here, and apologies I'm being a bit slow on replies.  It does indeed look like you fixed the issue I detected, which is great.  I'd like to poke at the code a little bit more to make sure I'm understanding it all, but before I dig too deep on this implementation, I wanted to ask:

Playing with this, it seems that it would probably be even more natural to offer to disable the current app (rather than the last resized one).  For instance, if I have Firefox focused, then when I open the Easy Move+Resize menu, it offers "Disable for Firefox".  And, bonus, if Firefox is already disabled, then when it is focused, the menu can offer "Re-enable for Firefox".  What do you think?

**Comment by moffatman** [comment]
@dmarcotte 
I considered it but I had two reasons for this way instead

1. It might not work on some accessory windows rather than full apps
2. It wouldn't be possible to disable for full screen apps, where it can be the worst if misbehaving

The main reason I implemented this feature is because I run a full screen game in which alt-click is part of the controls. You can't see the menubar when playing, the only way to get to the controls for Easy Move+Resize is to alt-tab to your last window, out of fullscreen mode. So with this method of showing the last-dragged-app, you are able to disable for that game, but if it was only the current app, it wouldn't work. I feel like this workflow is pretty natural, when you on accident move the window while working, you will naturally go to disable Easy Move+Resize so it doesn't happen, but now it will offer to disable the app which just caused the problem.

**Comment by dmarcotte** [comment]
Ah, well reasoned!  Thanks, @moffatman.  "Disable last app" it is then.

I'll try to finish my review here soon---thanks again for the contribution and the patience.   Really appreciate it.

**Comment by moffatman** [comment]
@dmarcotte Going through my open PRs and saw this one was still here. Just a ping if you have the time.

**Comment by dmarcotte** [comment]
Thank you, @moffatman!  Really: _thank you_.  Thank you for this nudge, thank you for your patience, and thank you for contributing this great enhancement.  Let's get this overdue release out!

**Pull request merged**
